// Copyright (c) 2026 Bates LLC. All rights reserved.
//
// Achievement checks for `--selftest-parser`: the Lua data reader, achievements.lua in the shapes
// gen_achievements.py may write, the launcher's progress snapshot, and how the two merge. Files
// go to a temporary folder; nothing is fetched and nothing of the game's is read.

import Foundation

extension CompanionSelfTest {
    /// Shape A: sets, each with its achievements list and a nested mapping per achievement.
    static let achievementsLuaNested = #"""
    -- Vanaguide :: data/achievements.lua
    -- GENERATED by tools/gen_achievements.py.  Do not hand-edit.
    local A = {}

    A.sets = {
        {
            game_id = 28275, title = 'Final Fantasy XI',
            achievements = {
                { id = 282751, title = 'A "quoted" start', description = "Complete \"The Rescue Drill\".\nAgain.",
                  points = 5, type = 'progression', badge = '1', display_order = 1,
                  target = { kind = 'quest', area = 'sandoria', id = 10, confidence = 'high' } },
                { id = 282752, title = 'Not yet', description = [[Obtain the Rank 2 key item.]],
                  points = 10, type = nil, badge = '2', display_order = 2,
                  target = { kind = 'key_item', id = 94 }, confidence = 'medium' },
                { id = 282753, title = 'Unmapped', description = 'Do something only a player can judge.',
                  points = 25, type = 'missable', badge = '3', display_order = 3 },
            },
        },
        {
            game_id = 28303, title = 'Hero of Nations',
            achievements = {
                { id = 283031, title = 'Nation hero', description = 'Rank 10.', points = 50, display_order = 1,
                  targets = { { kind = 'mission', area = 'sandoria', id = 20 }, { kind = 'zone', id = 230 } } },
            },
        },
    }

    return A
    """#

    /// Shape B: a flat map keyed by achievement id with the set id on each record.
    static let achievementsLuaFlat = #"""
    return {
        [282751] = { game_id = 28275, title = 'First', description = 'x', points = 5, order = 2 },
        [282752] = { game_id = 28275, title = 'Second', description = 'y', points = 10, order = 1,
                     quest = { area = 'sandoria', id = 10 } },
        [-1] = 'not a record', note = 1 + 2,
    }
    """#

    static func snapshotJSON(fetchedAt: Int, source: String = "RetroAchievements") -> String {
        #"""
        { "source": "\#(source)", "user": "Daniel", "fetched_at": \#(fetchedAt),
          "games": [ { "game_id": 28275, "title": "Final Fantasy XI", "earned": 1, "total": 3,
                       "achievements": {
                         "282751": { "earned_at": "2026-09-20T03:04:05Z", "earned_hardcore_at": null },
                         "282752": { "earned_at": null, "earned_hardcore_at": null },
                         "282753": { "earned_at": null, "earned_hardcore_at": null } } },
                     { "game_id": 28547, "title": "Hardcore Hero", "earned": 0, "total": 1,
                       "achievements": { "285471": { "earned_at": null, "earned_hardcore_at": null,
                                                     "title": "Only in the snapshot", "description": "From the launcher.",
                                                     "points": 3 } } } ] }
        """#
    }

    static func achievementChecks(guides: [Guide]) -> [(String, Bool)] {
        var checks: [(String, Bool)] = []
        func check(_ n: String, _ ok: Bool) { checks.append((n, ok)) }

        // Lua reader basics.
        let lt = LuaDataReader.tables(in: #"local X = { a = 1, ['b c'] = "two", [3] = -4.5e1, 0x10, true, nil, f(1), { 'n' }; --[[ c ]] z = [==[long]]x]==] } return X"#)
        let t = lt.first
        check("lua: one top-level table", lt.count == 1)
        check("lua: keyed, bracketed and numeric keys",
              t?["a"]?.int == 1 && t?["b c"]?.string == "two" && t?["3"] == .number(-45))
        check("lua: positional values, nil, call as other, nested table",
              t?.array.count == 5 && t?.array[0].int == 16 && t?.array[1] == .bool(true)
                  && t?.array[2] == .null && t?.array[3] == .other && t?.array[4].table?.array.first?.string == "n")
        check("lua: block comment skipped, long string with level", t?["z"]?.string == "long]]x")
        check("lua: escapes", LuaDataReader.tables(in: #"{ s = 'a\'b\n\65\x42\u{E9}' }"#).first?["s"]?.string == "a'b\nAB\u{E9}")

        // achievements.lua, nested shape.
        let a = AchievementData.parse(achievementsLuaNested)
        check("achievements.lua (sets): two sets", a.sets.map(\.id) == [28275, 28303]
                  && a.sets.first?.title == "Final Fantasy XI")
        check("achievements.lua (sets): four achievements, set id inherited",
              a.achievements.map(\.id) == [282751, 282752, 282753, 283031]
                  && a.achievements.first?.gameID == 28275 && a.achievements.last?.gameID == 28303)
        let first = a.achievements.first
        check("achievements.lua: fields",
              first?.title == #"A "quoted" start"# && first?.description == "Complete \"The Rescue Drill\".\nAgain."
                  && first?.points == 5 && first?.type == "progression" && first?.badge == "1" && first?.order == 1)
        check("achievements.lua: mapping and confidence",
              first?.targets.first?.kind == "quest" && first?.targets.first?.fields["area"] == "sandoria"
                  && first?.targets.first?.fields["id"] == "10" && first?.confidence == "high"
                  && a.achievements[1].confidence == "medium" && a.achievements[1].targets.first?.kind == "key_item")
        check("achievements.lua: unmapped keeps its description only",
              a.achievements[2].targets.isEmpty && a.achievements[2].description.hasPrefix("Do something")
                  && a.achievements[2].type == "missable")
        check("achievements.lua: a list of targets", a.achievements[3].targets.map { $0.kind ?? "" } == ["mission", "zone"])
        let flat = AchievementData.parse(achievementsLuaFlat)
        check("achievements.lua (flat map): ids from keys, order respected, junk ignored",
              flat.achievements.map(\.id) == [282752, 282751] && flat.achievements.allSatisfy { $0.gameID == 28275 })
        check("achievements.lua (flat map): quest = { area, id } is a quest target",
              flat.achievements.first?.targets.first?.kind == "quest"
                  && flat.achievements.first?.targets.first?.fields["id"] == "10")

        // Guide links: the fixture guide accepts sandoria,10 (QA) and turns it in (Q).
        if let g = guides.first {
            let questTarget = a.achievements[0].targets[0]
            check("quest target matches the guide's QA/Q steps",
                  questTarget.matches(g.steps[0]) && questTarget.matches(g.steps[4]) && !questTarget.matches(g.steps[1]))
            check("key item target does not match unrelated steps",
                  !g.steps.contains { a.achievements[1].targets[0].matches($0) })
        }

        // The progress snapshot.
        let fm = FileManager.default
        let dir = fm.temporaryDirectory.appendingPathComponent("vgc-selftest-\(UUID().uuidString)")
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: dir) }
        let now = Date(timeIntervalSince1970: 1_790_000_000)
        let freshURL = dir.appendingPathComponent("fresh.json")
        let oldURL = dir.appendingPathComponent("old.json")
        let badURL = dir.appendingPathComponent("bad.json")
        try? snapshotJSON(fetchedAt: 1_790_000_000 - 600).write(to: freshURL, atomically: true, encoding: .utf8)
        try? snapshotJSON(fetchedAt: 1_790_000_000 - 3 * 86400).write(to: oldURL, atomically: true, encoding: .utf8)
        try? snapshotJSON(fetchedAt: 1_790_000_000, source: "Other").write(to: badURL, atomically: true, encoding: .utf8)
        let fresh = ProgressSnapshot.read(freshURL)
        check("snapshot: contract shape decodes",
              fresh?.user == "Daniel" && fresh?.games.count == 2 && fresh?.games.first?.earned == 1
                  && fresh?.games.first?.achievements["282751"]?.earned == true
                  && fresh?.games.first?.achievements["282752"]?.earned == false)
        check("snapshot: missing file and foreign source are no data",
              ProgressSnapshot.read(dir.appendingPathComponent("none.json")) == nil && ProgressSnapshot.read(badURL) == nil)
        check("snapshot: stale after a day", fresh?.isStale(now: now) == false
                  && ProgressSnapshot.read(oldURL)?.isStale(now: now) == true)
        let registry = dir.appendingPathComponent("registry.json")
        try? JSONEncoder().encode([oldURL.path, dir.appendingPathComponent("gone.json").path, freshURL.path])
            .write(to: registry)
        let paths = ProgressSnapshot.candidatePaths(registry: registry, chosen: nil)
        check("snapshot: registry read, newest fetch wins over list order",
              paths.count == 3 && ProgressSnapshot.newest(paths)?.0 == freshURL)

        // Merge.
        let m = AchievementMerge.merge(data: a, snapshot: fresh, now: now)
        let ffxi = m.first { $0.id == 28275 }
        check("merge: sets from data then snapshot", m.map(\.id) == [28275, 28303, 28547])
        check("merge (fresh): earned, not earned",
              ffxi?.earnedRows.map(\.id) == [282751] && ffxi?.remaining.map(\.id) == [282752, 282753]
                  && ffxi?.remaining.allSatisfy { $0.state == .notEarned } == true && ffxi?.earned == 1)
        check("merge: a set the snapshot does not cover is unknown, not unearned",
              m.first { $0.id == 28303 }?.rows.allSatisfy { $0.state == .unknown } == true)
        check("merge: a set only in the snapshot is named from it",
              m.first { $0.id == 28547 }?.rows.first?.info.title == "Only in the snapshot"
                  && m.first { $0.id == 28547 }?.rows.first?.info.points == 3)
        let stale = AchievementMerge.merge(data: a, snapshot: ProgressSnapshot.read(oldURL), now: now).first { $0.id == 28275 }
        check("merge (stale): earned stays earned, the rest unknown",
              stale?.earnedRows.map(\.id) == [282751] && stale?.remaining.allSatisfy { $0.state == .unknown } == true)
        let none = AchievementMerge.merge(data: a, snapshot: nil, now: now)
        check("merge (no snapshot): everything unknown, nothing claimed unearned",
              none.flatMap(\.rows).allSatisfy { $0.state == .unknown } && none.count == 2)
        check("merge (no data file): snapshot alone lists its achievements",
              AchievementMerge.merge(data: nil, snapshot: fresh, now: now).first?.rows.count == 3)

        // A real achievements.lua, when one exists in a Vanaguide root, must read cleanly.
        for root in CompanionState.vanaguideRoots {
            let f = root.appendingPathComponent("data/achievements.lua")
            guard fm.fileExists(atPath: f.path) else { continue }
            let real = AchievementData.load(f)
            check("real achievements.lua at \(root.path) reads at least one titled achievement",
                  (real?.achievements.count ?? 0) > 0 && real?.achievements.allSatisfy { !$0.title.isEmpty } == true)
            break
        }
        return checks
    }
}
