// Copyright (c) 2026 Bates LLC. All rights reserved.
//
// RetroAchievements in the companion. Two files, both only read:
//
//  * Vanaguide/data/achievements.lua: the achievement lists (generated by Vanaguide's
//    tools/gen_achievements.py): title, description, points, type, set, and a best-effort mapping
//    to guide targets (quest, mission, key item, zone, NM) with a confidence.
//  * retroachievements.json: the player's progress, written by the FFXI-on-Mac launcher (which
//    does the fetching) to <Ashita install>/config/addons/Vanaguide/. The companion finds it
//    through the launcher's registry in Application Support. It never goes online itself and
//    never touches the game.
//
// A missing or stale snapshot is "no progress data", never "not earned".

import Foundation

struct AchievementTarget: Equatable {
    /// Flattened scalar fields of the mapping (`kind`, `area`, `id`, `zone`, `name`, ...).
    var fields: [String: String]
    var keyOrder: [String]

    var kind: String? { fields["kind"] ?? fields["type"] }

    var label: String {
        keyOrder.filter { $0 != "confidence" }.compactMap { k in fields[k].map { k == "kind" || k == "type" ? $0 : "\(k) \($0)" } }
            .joined(separator: ", ")
    }

    /// Does this guide step reach this target? Tags per docs/GUIDE_FORMAT.md: Q/QA `area,id`,
    /// M `area,id`, KI id, IT `id[,count]`, Z zone.
    func matches(_ step: GuideStep) -> Bool {
        let k = (kind ?? "").lowercased()
        let area = fields["area"] ?? fields["log"] ?? fields["nation"]
        let id = fields["id"]
        func pair(_ tag: String) -> Bool {
            guard let area, let id, let v = step.tags[tag] else { return false }
            return v.replacingOccurrences(of: " ", with: "").lowercased() == "\(area),\(id)".lowercased()
        }
        switch k {
        case "quest": return pair("Q") || pair("QA")
        case "mission": return pair("M")
        case "key_item", "keyitem", "ki":
            return id != nil && step.tags["KI"] == id
        case "item":
            return id != nil && step.tags["IT"]?.split(separator: ",").first.map(String.init) == id
        case "zone":
            return id.flatMap(Int.init) != nil && step.zone == id.flatMap(Int.init)
                && step.tags.isEmpty
        default:
            return false
        }
    }
}

struct AchievementInfo: Equatable, Identifiable {
    var id: Int
    var gameID: Int?
    var title: String
    var description: String
    var points: Int?
    var type: String?
    var badge: String?
    var order: Int?
    var targets: [AchievementTarget] = []
    var confidence: String?
}

struct AchievementSetInfo: Equatable, Identifiable {
    var id: Int
    var title: String
}

enum AchievementData {
    static let mappingKeys = ["targets", "target", "mapping", "map", "maps", "guide"]

    /// Every achievement record in achievements.lua, whatever the file's exact nesting: a record
    /// is a table with a numeric id (or numeric key) and a title, and no `achievements` child.
    /// A table that has an `achievements` child is a set; its id/game_id is inherited.
    static func parse(_ text: String) -> (sets: [AchievementSetInfo], achievements: [AchievementInfo]) {
        var sets: [AchievementSetInfo] = []
        var out: [AchievementInfo] = []
        var seen = Set<Int>()

        func gameID(of t: LuaTable) -> Int? {
            (t["game_id"] ?? t["gameID"] ?? t["set_id"] ?? t["game"])?.int
        }

        func walk(_ v: LuaValue, key: String?, inheritedGame: Int?) {
            guard let t = v.table else { return }
            let hasChildList = t["achievements"]?.table != nil
            if hasChildList {
                let gid = gameID(of: t) ?? t["id"]?.int ?? key.flatMap { Int($0) } ?? inheritedGame
                if let gid, !sets.contains(where: { $0.id == gid }) {
                    sets.append(AchievementSetInfo(id: gid, title: t["title"]?.string ?? t["name"]?.string ?? "Set \(gid)"))
                }
                for c in t.children { walk(c.value, key: c.key, inheritedGame: gid) }
                return
            }
            let title = t["title"]?.string ?? t["Title"]?.string
            let id = t["id"]?.int ?? t["ID"]?.int
                ?? ((t["description"] != nil || t["points"] != nil) ? key.flatMap { Int($0) } : nil)
            if let title, let id {
                if seen.insert(id).inserted { out.append(record(t, id: id, title: title, game: inheritedGame)) }
                return
            }
            // A plain list of sets: { [28275] = "Final Fantasy XI" } style entries are not records.
            for c in t.children { walk(c.value, key: c.key, inheritedGame: inheritedGame) }
        }

        func record(_ t: LuaTable, id: Int, title: String, game: Int?) -> AchievementInfo {
            var a = AchievementInfo(
                id: id, gameID: gameID(of: t) ?? game, title: title,
                description: (t["description"] ?? t["Description"] ?? t["desc"])?.string ?? "",
                points: (t["points"] ?? t["Points"])?.int,
                type: (t["type"] ?? t["kind"])?.string,
                badge: (t["badge"] ?? t["badge_name"] ?? t["BadgeName"])?.string,
                order: (t["display_order"] ?? t["order"] ?? t["DisplayOrder"])?.int,
                confidence: t["confidence"]?.string)
            for mk in mappingKeys {
                guard let m = t[mk]?.table else { continue }
                // One target table, or a list of them.
                let list = m.array.compactMap(\.table) + m.keys.compactMap { m.hash[$0]?.table }
                if list.isEmpty || !m.keys.filter({ m.hash[$0]?.table == nil }).isEmpty {
                    a.targets.append(target(m))
                } else {
                    a.targets.append(contentsOf: list.map(target))
                }
            }
            // Mapping written straight onto the record: quest = { area = 'x', id = 1 }.
            for k in ["quest", "mission", "key_item", "ki", "item", "zone", "nm", "npc"] {
                guard let sub = t[k]?.table, sub.array.isEmpty else { continue }
                var tg = target(sub)
                if tg.fields["kind"] == nil { tg.fields["kind"] = k; tg.keyOrder.insert("kind", at: 0) }
                a.targets.append(tg)
            }
            if a.confidence == nil { a.confidence = a.targets.compactMap { $0.fields["confidence"] }.first }
            return a
        }

        func target(_ t: LuaTable) -> AchievementTarget {
            var f: [String: String] = [:]
            var order: [String] = []
            for k in t.keys {
                if let s = t.hash[k]?.string { f[k] = s; order.append(k) }
                else if let sub = t.hash[k]?.table {  // quest = { area = 'x', id = 1 }
                    if f["kind"] == nil { f["kind"] = k; order.insert("kind", at: 0) }
                    for sk in sub.keys { if let s = sub.hash[sk]?.string { f[sk] = s; order.append(sk) } }
                }
            }
            return AchievementTarget(fields: f, keyOrder: order)
        }

        for t in LuaDataReader.tables(in: text) { walk(.table(t), key: nil, inheritedGame: nil) }
        out.sort { ($0.gameID ?? 0, $0.order ?? Int.max, $0.id) < ($1.gameID ?? 0, $1.order ?? Int.max, $1.id) }
        return (sets, out)
    }

    static func load(_ url: URL) -> (sets: [AchievementSetInfo], achievements: [AchievementInfo])? {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return nil }
        return parse(text)
    }
}

// MARK: - Progress snapshot (written by the launcher)

struct ProgressSnapshot: Decodable, Equatable {
    struct Earned: Decodable, Equatable {
        var earnedAt: String?
        var earnedHardcoreAt: String?
        var title: String?
        var description: String?
        var points: Int?
        var type: String?
        enum CodingKeys: String, CodingKey {
            case earnedAt = "earned_at", earnedHardcoreAt = "earned_hardcore_at", title, description, points, type
        }
        var earned: Bool { earnedAt != nil || earnedHardcoreAt != nil }
        var date: String? { earnedHardcoreAt ?? earnedAt }
    }
    struct Game: Decodable, Equatable {
        var gameID: Int
        var title: String
        var earned: Int
        var total: Int
        var achievements: [String: Earned]
        enum CodingKeys: String, CodingKey { case gameID = "game_id", title, earned, total, achievements }
    }
    var source: String
    var user: String
    var fetchedAt: Int
    var games: [Game]
    enum CodingKeys: String, CodingKey { case source, user, fetchedAt = "fetched_at", games }

    var fetchedDate: Date { Date(timeIntervalSince1970: TimeInterval(fetchedAt)) }

    /// Older than a day: still shown (an earned achievement stays earned), but not trusted to
    /// say what is *not* earned.
    static let staleAfter: TimeInterval = 24 * 3600

    func isStale(now: Date = Date()) -> Bool { now.timeIntervalSince(fetchedDate) > Self.staleAfter }

    static func read(_ url: URL) -> ProgressSnapshot? {
        guard let d = try? Data(contentsOf: url),
              let s = try? JSONDecoder().decode(ProgressSnapshot.self, from: d),
              s.source == "RetroAchievements" else { return nil }
        return s
    }

    /// The launcher's registry of snapshot paths, newest written first.
    static var registryURL: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("HorizonXI-on-Mac/retroachievements-snapshots.json")
    }

    /// Of the candidate files, the readable one fetched most recently.
    static func newest(_ paths: [String]) -> (URL, ProgressSnapshot)? {
        paths.map { URL(fileURLWithPath: $0) }
            .compactMap { u in read(u).map { (u, $0) } }
            .max { $0.1.fetchedAt < $1.1.fetchedAt }
    }

    static func candidatePaths(registry: URL = registryURL, chosen: String?) -> [String] {
        var paths: [String] = []
        if let env = ProcessInfo.processInfo.environment["VANAGUIDE_RA_SNAPSHOT"], !env.isEmpty { return [env] }
        if let chosen, !chosen.isEmpty { paths.append(chosen) }
        if let d = try? Data(contentsOf: registry),
           let list = try? JSONDecoder().decode([String].self, from: d) { paths += list }
        return paths
    }
}

// MARK: - Merged view

enum EarnedState: Equatable {
    case earned(String?)
    /// Not earned as of a fresh snapshot.
    case notEarned
    /// Not in a fresh snapshot: missing file, stale file, or a set it does not cover.
    case unknown
}

struct AchievementRow: Identifiable, Equatable {
    var id: Int
    var info: AchievementInfo
    var state: EarnedState
}

struct AchievementSetView: Identifiable, Equatable {
    var id: Int
    var title: String
    var earned: Int?
    var total: Int
    var rows: [AchievementRow]
    /// Not earned, or not known to be: the to-do list.
    var remaining: [AchievementRow] { rows.filter { !$0.isEarned } }
    var earnedRows: [AchievementRow] { rows.filter(\.isEarned) }
}

extension AchievementRow {
    var isEarned: Bool { if case .earned = state { return true }; return false }
}

enum AchievementMerge {
    /// Combine the data file's lists with the progress snapshot. Sets come from either; a set only
    /// in the snapshot is listed from the snapshot's own titles and descriptions.
    static func merge(data: (sets: [AchievementSetInfo], achievements: [AchievementInfo])?,
                      snapshot: ProgressSnapshot?, now: Date = Date()) -> [AchievementSetView] {
        let fresh = snapshot.map { !$0.isStale(now: now) } ?? false
        var order: [Int] = []
        var titles: [Int: String] = [:]
        for s in data?.sets ?? [] where titles[s.id] == nil { order.append(s.id); titles[s.id] = s.title }
        for g in snapshot?.games ?? [] where titles[g.gameID] == nil { order.append(g.gameID); titles[g.gameID] = g.title }
        var infos: [Int: [AchievementInfo]] = [:]
        for a in data?.achievements ?? [] {
            let gid = a.gameID ?? 0
            if titles[gid] == nil { order.append(gid); titles[gid] = gid == 0 ? "Other" : "Set \(gid)" }
            infos[gid, default: []].append(a)
        }
        return order.map { gid in
            let game = snapshot?.games.first { $0.gameID == gid }
            var list = infos[gid] ?? []
            if let game {   // anything the data file lacks, named from the snapshot
                let known = Set(list.map(\.id))
                for (k, e) in game.achievements {
                    guard let id = Int(k), !known.contains(id) else { continue }
                    list.append(AchievementInfo(id: id, gameID: gid, title: e.title ?? "Achievement \(id)",
                                                description: e.description ?? "", points: e.points, type: e.type))
                }
                list.sort { ($0.order ?? Int.max, $0.id) < ($1.order ?? Int.max, $1.id) }
            }
            let rows = list.map { a -> AchievementRow in
                let e = game?.achievements[String(a.id)]
                let state: EarnedState
                if let e, e.earned { state = .earned(e.date) }         // earned stays earned, stale or not
                else if fresh, game != nil, e != nil { state = .notEarned }
                else { state = .unknown }
                return AchievementRow(id: a.id, info: a, state: state)
            }
            return AchievementSetView(id: gid, title: titles[gid] ?? "Set \(gid)",
                                      earned: game.map(\.earned), total: max(game?.total ?? 0, rows.count), rows: rows)
        }
    }
}
